[package]
name = "mqtt-client-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.21.0"
rustls-native-certs = "0.6.2"
rustls-pemfile = "1.0.2"
# webpki-roots = "0.23.0"
